version: "3.8"

services:
  nginx:
    image: nginx:stable
    ports:
      - "443:3000"
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - client
      - server
    restart: unless-stopped

  client:
    image: node:22
    ports:
      - "3001:3001"
    working_dir: /app
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./vite.config.ts:/app/vite.config.ts
      - ./yarn.lock:/app/yarn.lock
      - type: bind
        source: client_node_modules
        target: /app/node_modules
    command: sh -c "yarn install && yarn run client:start"

  server:
    image: node:22
    ports:
      - "3002:3002"
    working_dir: /app
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./yarn.lock:/app/yarn.lock
      - type: bind
        source: server_node_modules
        target: /app/node_modules
    command: sh -c "yarn install && yarn run server:start"

volumes:
  client_node_modules:
  server_node_modules:
